---
abstract: unknown
author:
  - unknown
build_requires:
  Log::Dispatch::Config::TestLog: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.113640'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-Supervisor
no_index:
  directory:
    - t
    - inc
requires:
  Hash::Util::FieldHash::Compat: 0
  MooseX::LogDispatch: 0
  MooseX::POE: 0.210
  POE: 1.0002
  POE::API::Peek: 2.13
  Set::Object: 0
  namespace::clean: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=POE-Component-Supervisor
  repository: https://github.com/nothingmuch/poe-component-supervisor
version: 0.07
